### ISSUE TITLE
Handling NaN and inf Values for GPU_STUMP

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#128]
This is a follow up to #115 to handle NaN/inf values in `gpu_stump`.

See #117 for `mstump`/`mstumped`

**Comment by seanlaw** [comment]
@mexxexx I am working on this now but am getting stuck with some of the logic. 

So, in both `stump` and `stumped`, I understand why we set all inf to nan at the beginning before we compute the means a d stddev. However, can you remind me again why we set all of the nan in `T_A` to zero, then compute the first profile, before setting all the nan in `T_B` to zero before computing the other profiles? Why is this order of operations important? Why is it that we don’t set the nan from both `T_A` and `T_B` to zero first before computing the first profile?

**Comment by seanlaw** [comment]
In the meantime, I will review the comments from this PR: https://github.com/TDAmeritrade/stumpy/pull/122

**Comment by mexxexx** [comment]
I think it was because of how `stamp.mass` works:

1. The first subsequence is calculated using `stump._get_first_stump_profile` which in turn calls `stamp.mass(T_B[start : start + m], T_A, M_T, Σ_T, start, excl_zone)`
2. `stamp.mass` in turn is a wrapper over `core.mass` and then applies an exclusion zone and returns a profile value + index. `core.mass` is called with the following arguments: `core.mass(Q, T, M_T, Σ_T)`. Note that here `Q=T_B[start : start + m]` and `T=T_A`.
3. Now this is important: `core.mass` **does not know the mean/std of Q**, even if they are actually stored in `M_T` and `Σ_T` respectively (in the case of `T_A==T_B`, s self-joins). `core.mass` doesn't, and shouldn't know that `Q` in this case is a subsequence of `T`, because in general there is no reason for it to be so.
4. Hence, `core.mass` always recalculates `μ_Q` and `σ_Q`. So, if we would set nan from `T_B` to zero beforehand, `core.mass` would assume that the first subsequence doesn't contain any nans, and return a wrong distance profile, because if `Q` contains any nan, then the whole distance profile should be inf. This is why, in `core.mass` we have the lines
```
if np.any(np.isnan(Q)):
    distance_profile[:] = np.inf
```
So by not replacing the nans of `T_B`, we can actually capture these cases.
5. However, lateron the means of `T_B` **are** known when computing the distance profile, so we store the information about the respective subsequences containing nans there, to not have any computation errors because of the fastmath mode.

**Comment by seanlaw** [comment]
@mexxexx This helps a ton and clarifies a lot! I couldn't quite figure out why things didn't "just work" when I naively updated how the distance was being computed but now I have a better idea of where I need to modify the code to account for all of the things that you mentioned. Thank you!

**Comment by seanlaw** [comment]
@mexxexx Your explanation helped me quickly identify that the change was pretty straightforward. The tests all passed now!
