### ISSUE TITLE
any interest in adding backtesting?

### ISSUE THREAD

**Issue by EricSchles** [TDAmeritrade/stumpy#154]
back testing is cool!  I've only been able to find libraries that implement for financial data:
* https://pypi.org/project/Backtesting/
* http://pmorissette.github.io/bt/
* https://qtpylib.io/docs/latest/index.html

Might be cool to add it to stumpy as a general purpose interface for this.  Thoughts?

**Comment by seanlaw** [comment]
> You take a forecast for any timeseries model against a known time period.  Then you compare the forecast against what actually happened.  So the forecast is "back tested" against previous data.

Originally posted by @EricSchles [here](https://twitter.com/EricSchles/status/1247331255760359431)

Thank you for engaging with us! It may be due to my lack of experience/understanding of backtesting (so please forgive my ignorance) but STUMPY is primarily focused on applications deriving from the core matrix profile computation (this is the core competency of package). Beyond time series chains, I'm not aware of any forecasting use cases that leverage the matrix profile and so, for now, backtesting is likely beyond the scope of STUMPY. 

Would Pandas be an option? To add another (popular) backtesting package to the list, the folks at Quantopian also offer [Zipline](https://www.zipline.io/) as an option, though, it is finance focused.

**Comment by seanlaw** [comment]
@EricSchles I'm gonna close this for now but feel free to re-open if there is anything to add (now or in the future). Thank you!
