### ISSUE TITLE
Add Annotation Vector Tutorial

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#177]
Here's the [original paper](https://www.cs.ucr.edu/~eamonn/guided-motif-KDD17-new-format-10-pages-v005.pdf)

[The accompanying site, code, and data is here](https://www.cs.ucr.edu/~hdau001/guided_motif_search/)

Here is the [KDD 2017 Talk](https://www.youtube.com/watch?v=GCTzJRQkLjU)

**Comment by alvii147** [comment]
Hi Sean! Thanks for the resources. I can work on this tutorial.

**Comment by seanlaw** [comment]
Thanks @alvii147!

**Comment by alvii147** [comment]
Hi @seanlaw I've been working on this tutorial, I had a few questions I wanted to run by you:

1. How long should a tutorial be? My tutorial for the annotation vectors paper is turning out to be a bit long, there are around 20 plots, some of which have subplots. The reason why it's this long is because I'm exploring all 4 examples provided in the research paper in detail. Is there some hard limit to how long you want the tutorial to be?
2. Is it okay if I upload the datasets uses in this tutorial to Zenodo? Currently the datasets are hosted on Google Drive, which is too secure to download from the command line without additional libraries.
3. This is a more general question. I noticed that the tutorials stumpy has currently do not have syntax highlighting for the code blocks. Is there something we can do about that? While I tried to keep my code snippets as readable as possible, I'm certain they will look messy without syntax highlighting.

**Comment by seanlaw** [comment]
> How long should a tutorial be? My tutorial for the annotation vectors paper is turning out to be a bit long, there are around 20 plots, some of which have subplots. The reason why it's this long is because I'm exploring all 4 examples provided in the research paper in detail. Is there some hard limit to how long you want the tutorial to be?

I think 20 plots is too much and your audience will likely not read it. If you haven't done so already, please refer to the the existing set of tutorials as they provide a good example of what is expected. Instead of 4 examples, choose one really illustrative example (maybe two at the most). Also, please try your best to follow the style and layout of existing tutorials where possible. At the end of the day, before going too far, please feel free to submit a work-in-progress PR so that I can provide feedback along the way.

> Is it okay if I upload the datasets uses in this tutorial to Zenodo? Currently the datasets are hosted on Google Drive, which is too secure to download from the command line without additional libraries.

Let's worry about that a little later. Before we upload a bunch of datasets to Zenodo, let's figure out exactly which examples we're keeping first. We've found that it is best to upload at the end right before the PR is merged.

> This is a more general question. I noticed that the tutorials stumpy has currently do not have syntax highlighting for the code blocks. Is there something we can do about that? While I tried to keep my code snippets as readable as possible, I'm certain they will look messy without syntax highlighting.

I have not looked into this and don't have an answer. However, if there is interest in adding syntax highlighting to notebooks (assuming that it is possible) then we should create a brand new issue for it since it will need to be applied to ALL of the existing tutorials too. It should not be a part of this issue/PR. Does that make sense?

**Comment by seanlaw** [comment]
> I've submitted a pull request with my first draft of the tutorial so I could get some detailed feedback from you. I haven't yet excluded any of the examples, I'll leave that to your judgement. Let me know which sections I should keep and which are not important. In addition, let me know how I can improve the tutorial.

Thank you and sounds good. I am a bit backlogged but I will try to find some time to go through it and get back to you ASAP.

> I noticed that the tutorials stumpy has currently do not have syntax highlighting for the code blocks. Is there something we can do about that?

I did a quick search and it looks like this might be relevant. Would you mind creating a new issue and testing this out while you wait for feedback?

https://nbsphinx.readthedocs.io/en/0.6.0/installation.html#Pygments-Lexer-for-Syntax-Highlighting

**Comment by alvii147** [comment]
@seanlaw done! I'll try looking into it soon.
