### ISSUE TITLE
Move all `naive_*` functions to the `naive` module

### ISSUE THREAD

**Issue by mexxexx** [TDAmeritrade/stumpy#356]
I noticed that in some test modules (i.e. I looked into test_core.py) and found definitions for naive functions (e.g. `naive_rolling_window_dot_product`).

Should we move all these functions to the `naive` module?

**Comment by seanlaw** [comment]
Not trying to defend it as I am indifferent either way but wanted to provide the rationale here. Generally, I only moved things into `naive.py` when there was more than one module using it. Otherwise, I would keep the naive implementation with the corresponding test. I may have missed some and I can see how this may be confusing for others. I am open to moving ALL naive implementations into `naive.py` if you are up for it

**Comment by mexxexx** [comment]
Okay, I was not aware this was the rationale. It makes sense to keep it like this and is probably less confusing.
