### ISSUE TITLE
Inaccurate results of multi-dimension motif discovery using MSTUMP

### ISSUE THREAD

**Issue by davejaivik** [TDAmeritrade/stumpy#368]
Based on [Matrix Profile VI](https://www.cs.ucr.edu/~eamonn/Motif_Discovery_ICDM.pdf) Paper and [Stumpy Documentation (Tutorial-Mutlidimensional Motif Discovery)](https://stumpy.readthedocs.io/en/latest/Tutorial_Multidimensional_Motif_Discovery.html) of the same, I'm trying to identify Multi-dimensional Motifs from  [PRONTO Dataset](https://zenodo.org/record/1341583).

After a bit of preprocessing of the data, and calculating multidimensional matrix profile, I plot the Elbow Curve as suggested in the tutorial. Based on the curve k=8 dimensions out of 31 are relevant. 
![Elbow_31](https://user-images.githubusercontent.com/40367099/111955010-f1f37780-8b0e-11eb-8b36-c7b7c4277101.png)

When I plot the motifs after selecting the varibels using MP subspace, and I get the following result. Now, even though there are aligned motifs, but not all of them are aligned.
![image](https://user-images.githubusercontent.com/40367099/111960425-c0ca7580-8b15-11eb-9c9d-065cb5712671.png)

Even when I try with subset of variables I get misaligned motifs.

**Comment by seanlaw** [comment]
@davejaivik Thank you for the question. I'm not familiar with the PRONTO dataset but can you please provide a minimal-reproducible code example to reproduce all of the work that you are showing above? Otherwise, it's hard for us to speculate as to what is happening.  Additionally, it isn't clear why there are multiple dashed lines and red highlights. Would you mind explaining?
