### ISSUE TITLE
Same Versions on Github and Pip doesn't match

### ISSUE THREAD

**Issue by enerjista** [TDAmeritrade/stumpy#372]
Hi,

I would like to mention that the version on the pip 1.8.0 doesn't match with the Github version. In the pip version of Stumpy with 1.8.0, there is no option of normalize:

`def mass(Q, T, M_T=None, Σ_T=None):
`
But I can see the normalize param the Github, I downloaded the Github version now and using it. 
`def mass(Q, T, M_T=None, Σ_T=None, normalize=True):
`
I just want to mention that.

**Comment by seanlaw** [comment]
@enerjista Thank you for submitting this issue and we apologize for the confusion. By design, the [API documentation](https://stumpy.readthedocs.io/en/latest/api.html) reflects the latest development version on Github, which are usually ahead of the latest version available on PyPI (v1.8.0 as of March 2021). This should be remedied in the next v1.9.0 release.
