### ISSUE TITLE
Understanding Matrix Profile Output for Constant Sections in Time Series Data

### ISSUE THREAD

**Issue by gerold-csendes-epam** [TDAmeritrade/stumpy#375]
Hi stumpy folks,

[EDIT]: please check my comment below where I reason why this issue is not a bug

when epxerimenting with your awesome package, I migh have come across a bug. I work with time where values quite often don't change and these "constant" periods can be longer than the optimal m. In such case, I would expect to have 0 mp values since if values dont change for >m time, than the distance should be zero if I am correct.

I use stumpy v1.8.0.

Let me provide a reproducible example:

```python
np.random.seed(1)
array1 = np.random.normal(loc=10, scale=1.5, size=10)
array2 = np.array([2.0, 2.0, 2.0, 2.0])  

myarray = np.concatenate([array1, array2]) 

m=3
mp = stumpy.stump(myarray, m, normalize=True) 

discord_idx = np.argsort(mp[:, 0])[-1]

fig, axs = plt.subplots(2, sharex=True, gridspec_kw={'hspace': 0}, figsize=(14,8))
plt.suptitle('Discord (Anomaly/Novelty) Discovery', fontsize='30')

axs[0].plot(myarray)
axs[0].set_ylabel('Raw time-series', fontsize='20')
rect = Rectangle((discord_idx, 0), m, 10, facecolor='lightgrey')
axs[0].add_patch(rect)
axs[1].set_xlabel('Time', fontsize ='20')
axs[1].set_ylabel('Matrix Profile', fontsize='20')
axs[1].axvline(x=discord_idx, linestyle="dashed")
axs[1].plot(mp[:, 0])
plt.show()
```

As you can see, the last 4 values don't change but still I get the following mp:

![bug-1](https://user-images.githubusercontent.com/74710495/116072267-279bfb00-a68f-11eb-8267-6c3fcf109f02.PNG)

I don't quite get it why this happens. Also it is not only strange that the last two mp values are not 0, but also why these differ. Am I missing something or is this actually unexpected behavior?

A related potential issue is, that stumpy doesn't give me an error or warning when I leave `normalize ` argument of `stumpy.stump` as default (True) though the variance of the last two subsequences are zero. That should at least throw a warning, right?

Thanks a lot for taking the time to review this issue.

**Comment by gerold-csendes-epam** [comment]
It seems like I have ignored  the fact that a wider exclusion zone is applied than I expected. I could find in the docs that the exclusion zone is `int(np.ceil(m / 3))` which in this case is 1.

Thus, if I extend the constant part of the time series so that there are enough constant subsequences to match another constant one, then I get zero distances, as expected.

```python
np.random.seed(1)
array1 = np.random.normal(loc=10, scale=1.5, size=10)
array2 = np.tile(np.array([2.0]), 6)

myarray = np.concatenate([array1, array2]) 
m=3
mp = stumpy.stump(myarray, m, normalize=False) 

discord_idx = np.argsort(mp[:, 0])[-1]

fig, axs = plt.subplots(2, sharex=True, gridspec_kw={'hspace': 0}, figsize=(14,8))
plt.suptitle('Discord (Anomaly/Novelty) Discovery', fontsize='30')

axs[0].plot(myarray)
axs[0].set_ylabel('Raw time-series', fontsize='20')
rect = Rectangle((discord_idx, 0), m, 15, facecolor='lightgrey')
axs[0].add_patch(rect)
axs[1].set_xlabel('Time', fontsize ='20')
axs[1].set_ylabel('Matrix Profile', fontsize='20')
axs[1].axvline(x=discord_idx, linestyle="dashed")
axs[1].plot(mp[:, 0])
plt.show()
```

![bug-2](https://user-images.githubusercontent.com/74710495/116078782-4ef6c600-a697-11eb-8bee-34d132814a61.PNG)

Maybe putting a little more emphasis may be worth in the docs?

On the normalization note I shared in the previous comment, I think it is still something worth dealing with

**Comment by seanlaw** [comment]
@gerold-csendes-epam Welcome to the STUMPY community and thank you for taking the time to provide a reproducible example! When I follow your code and do:

```
np.random.seed(1)
array1 = np.random.normal(loc=10, scale=1.5, size=10)
array2 = np.array([2.0, 2.0, 2.0, 2.0])  

myarray = np.concatenate([array1, array2]) 

m=3
mp = stumpy.stump(myarray, m, normalize=True) 

discord_idx = np.argsort(mp[:, 0])[-1]

fig, axs = plt.subplots(2, sharex=True, gridspec_kw={'hspace': 0}, figsize=(14,8))
plt.suptitle('Discord (Anomaly/Novelty) Discovery', fontsize='30')

axs[0].plot(myarray)
axs[0].set_ylabel('Raw time-series', fontsize='20')
rect = Rectangle((discord_idx, 0), m, 10, facecolor='lightgrey')
axs[0].add_patch(rect)
axs[1].set_xlabel('Time', fontsize ='20')
axs[1].set_ylabel('Matrix Profile', fontsize='20')
axs[1].axvline(x=discord_idx, linestyle="dashed")
axs[1].plot(mp[:, 0])
plt.show()
```

I get:

![normalize](https://user-images.githubusercontent.com/7473521/116076034-b72ab500-a661-11eb-9968-bff7018788d7.png)

Note that this is when `normalize=True`. 

> I work with time where values quite often don't change and these "constant" periods can be longer than the optimal m. In such case, I would expect to have 0 mp values since if values dont change for >m time, than the distance should be zero if I am correct.

So, there is one concept that you must keep in mind when performing a "self-join" and that is "trivial matches" that exist in the "exclusion zone". You can learn a little bit more [here](https://stumpy.readthedocs.io/en/latest/Tutorial_The_Matrix_Profile.html#Additional-Notes). Essentially, for every subsequence you ignore all nearby neighbors since they are likely to look like you. By default (and following the original papers), the exclusion zone is roughly set to `+/- m/4` relative to the starting index of the subsequence. Since you've chosen `m = 3` then the exclusion zone will be `+/- 1`. This means that for the constant part of your time series, `myarray[10:10+m]` will ignore `myarray[9:9+m]` and `myarray[11:11+m]`. So, subsequence `myarray[10:10+m]` must look elsewhere for its nearest neighbor instead. Similarly, `myarray[11:11+m]` will ignore `myarray[10:10+m]` and `myarray[12:12+m]` (this latter subsequence does not exist but you get the point). 

Now, you can convince yourself by placing an identical constant subsequence that is more than one exclusion zone away:

```
np.random.seed(1)
array1 = np.random.normal(loc=10, scale=1.5, size=10)
array2 = np.array([2.0, 2.0, 2.0, 2.0])  

myarray = np.concatenate([array2, array1, array2]) 

m=3
mp = stumpy.stump(myarray, m, normalize=True) 

discord_idx = np.argsort(mp[:, 0])[-1]

fig, axs = plt.subplots(2, sharex=True, gridspec_kw={'hspace': 0}, figsize=(14,8))
plt.suptitle('Discord (Anomaly/Novelty) Discovery', fontsize='30')

axs[0].plot(myarray)
axs[0].set_ylabel('Raw time-series', fontsize='20')
# rect = Rectangle((discord_idx, 0), m, 10, facecolor='lightgrey')
# axs[0].add_patch(rect)
axs[1].set_xlabel('Time', fontsize ='20')
axs[1].set_ylabel('Matrix Profile', fontsize='20')
# axs[1].axvline(x=discord_idx, linestyle="dashed")
axs[1].plot(mp[:, 0])
plt.show()
```

![normalize2](https://user-images.githubusercontent.com/7473521/116079130-73d24580-a665-11eb-96d3-70336b4331e8.png)

Also, it looks like the image you generated is using `normalize=False` but the exclusion zone rules still apply:

![non-normalize](https://user-images.githubusercontent.com/7473521/116076730-9dd63880-a662-11eb-8e88-55760a89db60.png)

Note that there currently is no way to change the exclusion zone size in STUMPY but that should change in version 1.9.0.

**Comment by seanlaw** [comment]
@gerold-csendes-epam You just beat me to it! 👍

**Comment by gerold-csendes-epam** [comment]
great timing, @seanlaw. Thanks a lot for such a quick and detailed reply. 

Can't wait to play with version 1.9.0!

**Comment by seanlaw** [comment]
> Maybe putting a little more emphasis may be worth in the docs?

This is a good suggestion. Instead of passing in the exclusion zone as a parameter to `stumpy.stump`, we will be providing a global configuration parameter called `config.STUMPY_EXCL_ZONE_DENOM = 4` so that when it gets changed once then it changes for the whole STUMPY ecosystem and exclusion zones will be consistently computed as `int(np.ceil(m / config.STUMPY_EXCL_ZONE_DENOM))` instead of `int(np.ceil(m / 4))`.

> On the normalization note I shared in the previous comment, I think it is still something worth dealing with

Would you mind elaborating more on this? I think that I am missing your point and I would like to better understand

**Comment by gerold-csendes-epam** [comment]
sorry for abandoning the discussion @seanlaw. Let me elaborate on my question of normalization but I actually think I already have the answer. So, when using the default `True` value for the `normalize` argument in [stump](https://stumpy.readthedocs.io/en/latest/api.html#stump), the function z-normalizes subsequences and in case of my 'constant' array, [2, 2, 2, 2] I would have expected to get an error for 0 division. 
I think I found the code that fixes the issue here [github](https://github.com/TDAmeritrade/stumpy/blob/main/stumpy/core.py#L231-L252) by substituting 0 std-s with 1s. Is this correct?

**Comment by seanlaw** [comment]
> sorry for abandoning the discussion @seanlaw. Let me elaborate on my question of normalization but I actually think I already have the answer. So, when using the default `True` value for the `normalize` argument in [stump](https://stumpy.readthedocs.io/en/latest/api.html#stump), the function z-normalizes subsequences and in case of my 'constant' array, [2, 2, 2, 2] I would have expected to get an error for 0 division. 
> 
> I think I found the code that fixes the issue here [github](https://github.com/TDAmeritrade/stumpy/blob/main/stumpy/core.py#L231-L252) by substituting 0 std-s with 1s. Is this correct?

Yes, that is correct!

**Comment by gerold-csendes-epam** [comment]
awesome, thanks! Closing the ticket, thanks a lot for your quality answers!
