### ISSUE TITLE
is exclusion zone length hard-coded? 

### ISSUE THREAD

**Issue by Ninimama** [TDAmeritrade/stumpy#379]
I tried to search in the webpage and the doc. It seems the exclusion zone: m/4 is hard coded. Could you please put it as the input to the functions?

**Comment by seanlaw** [comment]
@Ninimama In all versions of STUMPY including v1.8.0, the exclusion zone is hard coded so as to reproduce the published work (ultimately, we try to stick to the published work as much as possible so that all assumptions are consistent). However, in commit 10b26725b7d5a6b74ef416083860e48f168a46ce we added a global configuration parameter called `config.STUMPY_EXCL_ZONE_DENOM` which is currently set to the default value of `4`. This ensures that if/when you change this value that it is used consistently across all functions that require an exclusion zone. This will help users to avoid needing to remember that they need to pass an explicit exclusion zone everywhere and, instead, it should be set once. Of course, it still assumes that the exclusion zone is `np.ceil(m / config.STUMPY_EXCL_ZONE_DENOM).astype(int)` (i.e., always relative to the window size) but we believe that it is still very reasonable. 99% of users will likely never change this value.

**Comment by Ninimama** [comment]
@seanlaw: 
I understand your viewpoint. Yes, it is a good idea to provide flexibility while making sure that users don't make mistake in passing the exclusion zone to each function. Thanks for your response.
