### ISSUE TITLE
window_size 1 and 2 doesn't seem to work

### ISSUE THREAD

**Issue by pembeci** [TDAmeritrade/stumpy#45]
Even if `ignore_trivial` is explicitly set to `True`, there seems to be a problem when `m` is 1 or 2.

```
test = [3,8,9,2,5,1,17,4,11,18]
profile = stumpy.stump(np.float_(test), m=1, ignore_trivial = True)
print(profile)
print(2 ** 0.5)

[[1.4141633185218911 1 -1 -1]
 [1.4142135623730951 2 -1 -1]
 [1.4142135623730951 0 0 -1]
 [1.4142135623730951 0 0 -1]
 [1.4142135623730951 0 0 -1]
 [1.4142135623730951 1 1 -1]
 [1.4142135623730951 0 0 -1]
 [1.4142135623730951 1 1 -1]
 [1.4142135623730951 0 0 -1]
 [1.4142135623730951 0 0 -1]]
1.4142135623730951

test = [3,8,9,2,5,1,17,4,11,18]
profile = stumpy.stump(np.float_(test), m=2, ignore_trivial = True)
print(profile)

[[0.0 1 -1 -1]
 [0.0 3 -1 3]
 [0.0 4 0 4]
 [0.0 0 0 5]
 [0.0 2 2 6]
 [0.0 0 0 7]
 [0.0 2 2 -1]
 [0.0 0 0 -1]
 [0.0 0 0 -1]]
```

**Comment by seanlaw** [comment]
@pembeci Thanks for pointing this out and I can confirm this finding. 

It looks like the issue comes up when the z-normalization happens. In the case of `m=1`, z-normalization doesn't make any sense since the standard deviation for an array with only a single element will always be zero and, therefore, you get a divide by zero situation. So, `m` should never be equal to `1`. I'm assuming that the same/similar problem exists for `m=2`. In short, this isn't so much a fault of STUMPY but of the instability of the math for toy examples.

I believe that the situation is fine when the `m >= 3` or when `m` and the length of the array gets bigger and bigger.

As a user, would you mind providing some feedback as to how you might expect these scenarios to be handled? In the simplest case, we can always enforce that `m >= 3` and print a logging warning to let the user know that the value of `m` must be greater than or equal to 3. I'd love to hear your thoughts.

**Comment by pembeci** [comment]
Thanks for the detailed explanation Sean. I didn't have the time to look deeper in paper's math or code. As a user, I think both options (warning or ValueError) are fine as long as I am given notice of this limitation. From software engineering angle, ValueError may be a better option though. If this wasn't faced during exploratary/development phase, warning may get lost in a complex program utilizing STUMPY where m is computed dynamically. Feel free to close the issue whenever you like.
