### ISSUE TITLE
should we change the format of the output of `stumpy.motifs`?

### ISSUE THREAD

**Issue by Ninimama** [TDAmeritrade/stumpy#522]
I was wondering if we could change the output of `stumpy.motifs` as I think it might give weird results in its current implementation. 

**Example:**
```
df = pd.read_csv("https://zenodo.org/record/4603813/files/common_nightingale.csv?download=1")
T = df["mfcc_2"].to_numpy()

mp_mfcc2_150 = stumpy.stump(T, m=150)

motif_distances, motif_indices = stumpy.motifs(T, 
                                               mp_mfcc2_150[:,0], 
                                               min_neighbors=1, 
                                               max_distance=np.inf, 
                                               cutoff=np.inf,
                                               max_matches=10,
                                               max_motifs=5,
                                               normalize=True)

```

Gives the following output:

```
motif_indices: 
 [[ 2973 34474 28461 19243  7067 28266  9835 15720  9695  6203]
 [    0 26121 31938 27110 11000 31288 18085 19509 19726 25488]
 [    0 26121 31938 27110 11000 31288 18085 19509 19726 25488]
 [    0 26121 31938 27110 11000 31288 18085 19509 19726 25488]
 [    0 26121 31938 27110 11000 31288 18085 19509 19726 25488]]
```

I think it would be nice to use `-1` instead of repeating a motif index.

**Comment by seanlaw** [comment]
@Ninimama I am wondering if this is a small bug. With `max_motifs=5`, this means that at most `5` motifs will be returned (i.e., `5` rows). However, if there are no new motifs, then I would've expected only the first two rows to be returned. It should not be possible for a motif located at index `0` to be identified again as a motif since its distance should've been set to `np.inf`

**Comment by Ninimama** [comment]
I took a quick look at the code but couldn't figure it out. I can try again if you are busy with other things.

**Comment by seanlaw** [comment]
> I took a quick look at the code but couldn't figure it out. I can try again if you are busy with other things.

I might be able to get to it by the end of the day. Are you currently using this for something or were you just exploring? When I say "bug", I really mean that it needs to break after 2 motifs (assuming there are truly only 2 motifs that meet the criteria).

**Comment by seanlaw** [comment]
Okay, I see the issue. When you use `cutoff=np.inf` this is cause this line to be `False`:

https://github.com/TDAmeritrade/stumpy/blob/58adc79b4085c73dc7a781cdef094c10db9a1845/stumpy/motifs.py#L101-L102

However, if you switch to setting `cutoff=np.finfo('d').max` then this should produce the expected behavior of only returning the correct (one) motif. I will patch this edge case
