### ISSUE TITLE
Handle Constant Regions Consistently

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#591]
Currently, `stumpy.stump` and `stumpy.stumped` can account for constant regions. So, when two subsequences are being compared and one subsequence is constant (and the second is not constant) then the pearson correlation is set to `0.5`, which means that the z-normalized Euclidean distance is `np.sqrt(np.abs(2 * m * (1 - 0.5)))` or `np.sqrt(m)` (<s>not sure if this is the best/correct choice</s> see proof below). However, when both subsequences are constant then the pearson correlation is set to `1.0`, which means that the distance is `0.0`

However, this is unaccounted for in `stumpy.mstump` and `stumpy.mstumped` and `stumpy.gpu_stump` and `stumpy.mass` and some `tests/naive.py` implementatios. This may be something we should consider doing consistently everywhere.

<details>
<summary>changes to `_mass`</summary>

Replace the return statement with:
```
distance_profile = calculate_distance_profile(m, QT, μ_Q, σ_Q, M_T, Σ_T)
if σ_Q == 0.0:
    # Both subsequences are constant
    distance_profile[Σ_T == 0.0] = 0.0
else:
    # Only one subsequence is constant
    distance_profile[Σ_T == 0.0] = math.sqrt(m)

return distance_profile
```
</details>

[This paper](https://core.ac.uk/download/pdf/287941767.pdf) may offer some direction/insight as to how best to handle this.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Very interesting. I have not read the paper yet. This is just what I think:

I think we should simply replace a constant subsequence with all zeros (after z-normalization). 

So, let's say we have:

```
import numpy as np
s = np.full(n, a, dtype=np.float64)
```
Then, removing the offset (i.e. `s_0 = s - s.mean()`) becomes all 0. It does not matter what value of `a`  we have. 

Now, the question is: "How about standard deviation?" Because if we consider `std=0`, then `s_0/0` is not defined. I THINK we can assume that std is very very small, and thus `s_znorm = s_0 / std` become 0. In fact, it does not matter what `std` we choose 
as long as it is not zero, and I think it is okay! I think it is NOT meaningLESS. 

So, let us say we have two other subsequences as follows:

```
# s2 --> has length n, mean 0, and it may look like a sine wave, with `std` of 1
# s3 --> has length n, mean 0, and it may look like a sine wave but with higher peak and lower valleys, with `std` of 2
```
it seems meaningful that `d(s2, s3, normalize=True)` is 0 (because they are similar). AND, it is also meaningful that their z-normalized distance to a constant subsequence `s` is basically the distance between their z-normalized version and an all-zero subsequence.

Please let me know if my explanation makes sense.

**Comment by NimaSarajpoor** [comment]
Another thing that just came to my mind and I thought it might be worth sharing:

If you notice, the domain of values of z-normalized version of a non-constant subsequence with length `m` is `R^{m}` space excluding `0` (the origin). Replacing a constant subsequence with all-zero subsequence can make our domain cover the whole space.

**Comment by NimaSarajpoor** [comment]
That is correct and it is aligned with the concept of replacing a constant subsequence with all 0. I will provide a link to its proof.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
And, one more thing: it would be nice if someone can read the paper and see if the authors investigate this matter further or not. I can read it if I get some free time in the future.

**Comment by seanlaw** [comment]
> @seanlaw : I guess it´s correct if the other one is random. But as it is the case now in `.mass()` it is set to `sqrt(m)` independent of the other one which is not correct imho.

Yes, this is not fixed in `mass` yet. This current issue, when resolved, would/should also require fixing `mass` too

**Comment by NimaSarajpoor** [comment]
@seanlaw 
**Update (might be of your interest)**

I took a look at [the paper](https://core.ac.uk/download/pdf/287941767.pdf). It seems it is about handling noise in time series data and how it affects the matrix profile distance. Apparently, noise has higher impact on flatter (!) subsequences. So, if I understand correctly, their work is not about handling the constant subsequence `S`. It is about handling the subsequence `S'`, where  `S' = S + noise`, and `S` is constant. 


**See Section 4** Paragraph 1:
> While the utility of the z-normalized Euclidean distance as a shape-comparator has been proven by the many Matrix Profile related publications [22, 24, 12], results become counter-intuitive for sequences that contain subsequences that are flat, with a small amount of noise.

---

Their observations sounds interesting (see Fig. 4 and its caption), and the topic (i.e. handling noise) can have its own, separate issue. The core idea is to (somehow?) estimate `\sigma_noise` and then modify the z-normalized Euclidean Distances using formula provided in Algorithm1.

**Comment by seanlaw** [comment]
Thanks @NimaSarajpoor! I remember skimming the paper when it first came out and had the impression that it may be a "nice to have" (but not default) but not a "must have" because it isn't super obvious and adds some overhead. I only linked to the paper in case it could possibly help us deal with purely constant subsequences. I think the fix for this issue should be straightforward given the two cases.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
I see. So, for instance, we may add a noise to avoid divide-by-zero issue in z-normalizing constant subsequences, and then use the  proposed method of paper to handle the noise! As you noticed, it is not super obvious, and I think it needs some investigation on how it affects the results and if the final outcome is reasonable(?) or not.

**Comment by NimaSarajpoor** [comment]
**A few notes**

* I derived `eq(7)` of paper, and it is correct. 
* The formula in Algorithm 1 has a typo. The correct one is provided in the section 3.2 of the author's [previous work](https://www.scitepress.org/Papers/2019/73141/73141.pdf)
* I think it is NOT CLEAR how they get from `eq(7)` to the Formula proposed in `Algorithm1`

---

**Results**

I also calculated the matrix profile of a noisy data that contains an anomaly, while considering Algorithm1 of paper (after fixing its typo). 

```
# Generating sine wave
T = np.array(list(map(math.sin, np.linspace(0, 100, 1000)))) 


# Add anomaly at index 280, with length 5
anomaly_idx = 280
anomaly_size = 5

T_with_anomaly = T.copy()
T_with_anomaly[anomaly_idx : anomaly_idx + anomaly_size] += 0.5 


# Add noise
n_T = len(T_with_anomaly)

seed = 0
np.random.seed(seed)
T_with_anomaly_with_noise =  T_with_anomaly.copy() + np.random.normal(0, 0.05, size=n_T) 
```

![image](https://user-images.githubusercontent.com/38519522/168464633-7148c2aa-788a-46a2-b7c2-724bd91c3e0a.png)

Now, let us plot the **Regular Matrix Profile (i.e. no modification)** and **Modified Matrix Profile (i.e. considering noise elimination)** below (for `m=8`):

![image](https://user-images.githubusercontent.com/38519522/168465401-d405c1ef-006f-48e9-bb62-e397aff50b78.png)

![image](https://user-images.githubusercontent.com/38519522/168465434-5d30995b-61ab-49e8-8135-82a21ae77890.png)

We can see the modified version can better detect anomaly for `m=8`. 


Alternatively, as noted in the paper, we can just use `Regular Matrix Profile` but with bigger (longer) window size:

![image](https://user-images.githubusercontent.com/38519522/168465357-cf32b6ef-8d39-44f0-9b24-8fda35746a78.png)

We can see that longer `m` resolve the impact of z-normalization on noisy constant subsequences.

----

**How to add it to `stumpy.stump`?**

To use this in `stumpy.stump`, we can add parameter `sigma_noise=0` and then, we can modify `rho` in O(1) time as follows:
```
Pearson_modified[i, j] = Pearson[i, j] + ( (1 + m) / m) * ( sigma_noise / (1e-06 + max(sigma_i, sigma_j)) ) ** 2
```

---

**How can we use it for constant subsequence?**

Let us take a look at the example below:

![image](https://user-images.githubusercontent.com/38519522/168466646-093812d3-9442-47f9-abfb-7df988d6dab9.png)

And, let us take a look at the distance profile of the highlighted subsequence (after ignoring its trivial matches):

![image](https://user-images.githubusercontent.com/38519522/168466686-249e4bca-b6e1-4ec0-9319-cd92cfb894a8.png)

The match is the other constant subsequence in the data. But, we can see there are two other ALMOST constant subsequences as follows. We also added a huge noise on one of the subsequences (located on the right of time series data). Now, let us take a look the modified distance profile:


![image](https://user-images.githubusercontent.com/38519522/168466915-9667bd13-7339-45fc-b99e-32becf2efe14.png)


So, considering `\sqrt(m)` might be too harsh and letting user play with `sigma_noise` might be useful!

**Comment by seanlaw** [comment]
@NimaSarajpoor Thank you for looking into this and for verifying that it does indeed work! To be clear, this current issue is focused on handling perfectly constant regions with zero noise but making sure that it is consistent across all z-normalized distance calculations as, right now, it is only handled in `stumpy.stump` and `stumpy.stumped` but missing in others. Let's track "constant regions with noise" in this [other (original) issue](#127).

**Comment by NimaSarajpoor** [comment]
Thanks for the clarification. I was actually trying to see if we can borrow an idea from the paper but I think I should better not go to that route. 

I also found the results interesting but didn't know there was an issue about this before. Thanks for reopening that! I have some thoughts about handling noise and I will share them in that issue. Sorry for going off-road in this issue.

**Comment by JaKasb** [comment]
I also expiremented the with the noise compensation method:
Many aspects in the realm of matrix profiles algorithms suffer from instability in edge cases:

#### How to choose sigma_n ?
Set sigma_n too small and the correction has no effect.
Set sigma_n too large and the correction overshoots and results in negative euclidean distances.
Even with reasonable sigma_n, the compensation needs safeguard measures to protect against negative distances.
I derived a supremum for sigma_n, by assuming Pearson Correlation of -1 and solving for sigma_n in
E[D²] = max_possible_distance²
```
_denom = np.maximum(sigma_i, sigma_j)**2
# https://www.wolframalpha.com/input?i=solve+%282*m+%2B+2%29+*%28x%5E2%29%2F%28d%29+%3D+4m+for+x+and+d%3E0+and+m%3E0
supremum_sigma_n = np.sqrt(2) * np.sqrt(_denom*m/(m+1))
sigma_n = np.clip(sigma_n, a_min=0, a_max=supremum_sigma_n)
E_d_squared_max = (2*m + 2)*(supremum_sigma_n**2)/_denom
assert np.allclose(E_d_squared_max, 4*m)
```
However, this upper limit on sigma_n is useless in practice, because the expected value of the pearson correlation is ca 0, as opposed to -1.

#### Assumptions
The method flatout assumes Gaussian Noise, however constant subsequences often stem from quantization errors.
The probability density function of the quantization error is Uniform instead of Gaussian.
https://www.allaboutcircuits.com/technical-articles/quantization-nois-amplitude-quantization-error-analog-to-digital-converters/

#### Comparison to Annotation Vector
The noise compensation method can be interpreted as a special case of the Annotaion Vector framework.
https://dl.acm.org/doi/pdf/10.1145/3097983.3097993
`Corrected Distance = dist + (1-AV)*max_distance`
compared to
`corrected distance = sqrt(dist² - E[D²]`
The negative of E[D²]  *is* an Annotation Vector. 

Because E[D²] can be reduced to: `constant_factor * 1/np.std(subsequence)` :
The benefit of the AV-framework is that the AV is normalized to 0..1, therefore the constant factor is less of a problem, therefore the choice of sigma_n is not as sensitive.

#### Comparison to CID
https://www.researchgate.net/publication/254861501_CID_An_efficient_complexity-invariant_distance_for_time_series
As a reminder, the time series complexity measure is the "length" of a time-series if the time series were a rope.
I assume that E[D] and Complexity are highly correlated:
If the subsequence is flat the complexity is low and std() are low.
If the subsequence is squiggly, then the complexity and std() are high.
EDIT: A quick experiment shows only weak correlation ?!

#### Choice of Expected-Value as predictor
The Expected Value is a good predictor if both subsequences are noise and uncorrelated.
In the case of a perfect motif match (euclidean distance = 0) the Expected Value is very off.
Analyzing the histogramm of euclidean distances can be very misleading, because the motif-matches are strong outliers in the overall histogramm.
The matrix-profile lies the outer edge of the fat tails of the distance histogramm.
There are some papers that study the histogram of the distance-matrix and the matrix profiles, but that only works on some types of time series.
Maybe a Baysian Interpretation could be helpful ?
(Given sigma_x and sigma_y how likely is the observed euclidean distance ?)
