### ISSUE TITLE
Parallelize `mass` function

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#720]
Currently, `stumpy.mass` is only single threaded. However, there might be a way to parallelize things by chunking the arrays into `n_threads` number of parts. However, note that this can't be done in the `_mass` function since `_mass` must be kept as `parallel=False` due to `scrump._compute_PI` being single threaded and calls `_mass`. Instead, we can have `mass` call a new function called `_mass_dispatcher` (this is where the chunking into multiple threads happens), which ultimately calls `_mass` on different chunks.

**Comment by seanlaw** [comment]
I've experimented with this and it appears that there is **no** performance gain:

```
import numpy as np
from numba import njit, prange
import time
import stumpy
from stumpy import core
import numba
import numpy.testing as npt

@njit(
    parallel=True,
    fastmath=True,
)
def _mass_dispatcher(Q, T, QT, μ_Q, σ_Q, M_T, Σ_T):
    out = np.empty(len(QT))
    n_threads = numba.config.NUMBA_NUM_THREADS
    ranges = core._get_ranges(len(T), n_threads, False)
    for thread_idx in prange(n_threads):
        start, stop = ranges[thread_idx]
        out[start:stop] = core._mass(Q, 
                                     T[start:stop],
                                     QT[start:stop],
                                     μ_Q,
                                     σ_Q,
                                     M_T[start:stop],
                                     Σ_T[start:stop]
                                    )
    return out


def mass_dispatcher(Q, T):
    m = Q.shape[0]
    QT = core.sliding_dot_product(Q, T)
    T, M_T, Σ_T = core.preprocess(T, m)
    μ_Q, σ_Q = core.compute_mean_std(Q, m)
    μ_Q = μ_Q[0]
    σ_Q = σ_Q[0]
    return _mass_dispatcher(Q, T, QT, μ_Q, σ_Q, M_T, Σ_T)


if __name__ == "__main__":
    Q = np.random.rand(50)
    T = np.random.rand(10_000_000)
    
    start = time.time()
    dispatch = mass_dispatcher(Q, T)
    print(time.time() - start)
    
    start = time.time()
    cmass = core.mass(Q, T)
    print(time.time() - start)

    npt.assert_almost_equal(dispatch, cmass)

# 0.47920799255371094
# 0.46747279167175293
```

**Comment by JaKasb** [comment]
1. Does numba really parallelize ?
Hint: Observe htop during execution. Increase problem size, such that mass-runtime >= htop-update-rate. 3 second should suffice.

2. Does numba even parallelize nested functions ?
```
@njit(parallel=True)
def outer_function():
    for foo in prange():
        inner_function(foo)
```
Where the inner function is already specified with
```
@njit(parallel=False)
def inner_function():
    bar()
```
The inner functions in `_mass()` are decorated with `@njit(fastmath=True)` which implicitly specifies `parallel=False`.

3. If `_mass ` does release the GIL, then a simple `map()` would be enough for parrallel execution.
No need for `prange`.

4. Maybe explicitly parallelize at this loop in `_calculate_squared_distance_profile`
https://github.com/TDAmeritrade/stumpy/blob/97d7bd623d386281c705d340be07d5c94231b583/stumpy/core.py#L1000

5. Maybe the bottleneck is the dispatcher:
```
    QT = core.sliding_dot_product(Q, T)
    T, M_T, Σ_T = core.preprocess(T, m)
    μ_Q, σ_Q = core.compute_mean_std(Q, m)
```

6. The original MASS homepage shows a speedup by using Overlap-Add convolutions:
Related: https://github.com/TDAmeritrade/stumpy/issues/304
Maybe perform the 1D-convolution on the GPU ?

7. BTW is mass() really too slow ?
After all, mass is in O(n log n). In my use cases, mass was "fast enough".
In order to avoid blind "yak shaving" and optimizing non-bottlenecks, profiling the `mass()` function could be insightful.

**Comment by seanlaw** [comment]
> Maybe the bottleneck is the dispatcher:
>    QT = core.sliding_dot_product(Q, T)
    T, M_T, Σ_T = core.preprocess(T, m)
    μ_Q, σ_Q = core.compute_mean_std(Q, m)

You're right! The majority of the time is spent in the sliding-dot-product and the pre-processing steps and the actual `mass` part is negligible. We'll be working on something to improve the speed of the pre-processing step but I don't think there's anyway to speed up the sliding-dot-product.

> BTW is mass() really too slow ?

No, I didn't think so but a user had a question and I realized that `mass` was not parallelized and wanted to do a quick exploration.
