### ISSUE TITLE
Potential issues in `floss`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#811]
Before moving forward with #810, I think the `floss` module needs to be investigated regarding the following issues:

1)

https://github.com/TDAmeritrade/stumpy/blob/c06f0e998d28e7b717bab1e4e32a2aeb897ddfc3/stumpy/floss.py#L561-L566

`self._mp[-1,3]` should be set to the last index. But, `self._last_idx` is set as:
https://github.com/TDAmeritrade/stumpy/blob/c06f0e998d28e7b717bab1e4e32a2aeb897ddfc3/stumpy/floss.py#L478

So, I was wondering if we should change the code above to `self._last_idx = self._n - self._m`

2)

https://github.com/TDAmeritrade/stumpy/blob/c06f0e998d28e7b717bab1e4e32a2aeb897ddfc3/stumpy/floss.py#L584

In code above, `self._T_isfinite` is a boolean array. I think this line should be changed to:
```
self._T_isfinite = core.rolling_isfinite(self._T, self._m)
```

Also, if we are just shifting or updating, why should we recompute the full array everytime?

3) 

https://github.com/TDAmeritrade/stumpy/blob/c06f0e998d28e7b717bab1e4e32a2aeb897ddfc3/stumpy/floss.py#L568-L580

If I understand correctly, we are not removing the very first point in the time series in "ingress" mode. But, we already shift `self._T`, see below:

https://github.com/TDAmeritrade/stumpy/blob/c06f0e998d28e7b717bab1e4e32a2aeb897ddfc3/stumpy/floss.py#L546

So, shouldn't we seperate ingress / egress, like the code in `stumpy/stumpi.py` module.

---

I think it is worth it to investigate the aforementioned items and clean up this module if possible. I have not read the `floss` paper. So, my observation is purely based on the code itself.

**Comment by seanlaw** [comment]
> So, I was wondering if we should change the code above to self._last_idx = self._n - self._m

Man, you're really challenging me to remember why I did this three years ago! However, IIRC, I think the reason why it MUST BE `self._n - self._m + 1` is because for `floss` we have a moving window (egress + ingress = moving window) and, as each new data point arrives, its actual "real" index (relative to the original input time series) must be continually increasing by one.  For example, let's say we start off with a time series of length `n = 6` and window size of `m = 5`. When a new datapoint arrives, that last (newest) subsequence has no "right matrix profile index" and so we must set its "right matrix profile index" to itself. However, what is the "real" index value for that last (newest) subsequence given that we've egressed the first datapoint and then ingressed a new datapoint? Since it is the very first egress+ingress, it is actually set as `n - m + 1 = 6 - 5 + 1 = 2`. So, the last (newest) subsequence has a "right matrix profile index" that is pointing to itself (i.e., subsequence idx 2). Then we increment `last_idx` by one and await the next egress+ingress moving window event.

Does that make sense? I hope that helps.

> self._T_isfinite = core.rolling_isfinite(self._T, self._m)

That seems like a typo. Though, it's surprising that none of the tests failed or that we didn't hit some out-of-bound indexing. I do see that the corresponding `test_floss_inf_nan` unit test carries the same problem. Maybe we just got lucky and this needs to be fixed!

> So, shouldn't we seperate ingress / egress, like the code in stumpy/stumpi.py module.

For `floss`, there is no "ingress" mode at all. It's a moving window so one point is ingressed and the oldest points is egressed. In order to represent/handle the moving window, we must first egress the oldest data point first and then we record the newest datapoint.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
> Man, you're really challenging me to remember why I did this three years ago!

Sorry about this! :) It is hard for me to let things go easily :smile: 

> its actual "real" index (relative to the original input time series) must be continually increasing by one

Thank you for the explanation. Now I can get it..the index reflects the position of subsequence with respect to the original time series.

> That seems like a typo. Though, it's surprising that none of the tests failed or that we didn't hit some out-of-bound indexing. I do see that the corresponding test_floss_inf_nan unit test carries the same problem. Maybe we just got lucky and this needs to be fixed!

I thought we made mistake in computing both `ref` and `comp` values. However, I now think that `ref` is correct. Please see the following lines:

https://github.com/TDAmeritrade/stumpy/blob/c06f0e998d28e7b717bab1e4e32a2aeb897ddfc3/tests/test_floss.py#L305-L308

Here, we are using `np.all(core.rolling_window(....))` and that is correct. 

> For floss, there is no "ingress" mode at all. It's a moving window so one point is ingressed and the oldest point is egressed. 

Got it! I thought the naming is similar to `stumpi`, where we support two different modes. Thank you for the explanation.

**Comment by seanlaw** [comment]
> I thought we made mistake in computing both ref and comp values. However, I now think that ref is correct

What happens when you change `self._T_isfinite = core.rolling_isfinite(self._T, self._m)`? Do the unit tests still pass?

**Comment by NimaSarajpoor** [comment]
> What happens when you change `self._T_isfinite = core.rolling_isfinite(self._T, self._m)`? Do the unit tests still pass?

Yes. Locally, its unit tests are passing. Also: I just pushed a commit that fixes it in the performant version. Now, I think I should have put it on hold till I find the reason behind not getting error.

**Comment by seanlaw** [comment]
>  T_subseq_isfinite = core.rolling_isfinite(self._T_isfinite, self._m) 

For future reference, it turns out that this line is correct because:

1. `self._T_isfinite` corresponds to each element of `T` and not each subsequence of `T`
2. `core.rolling_isfinite` accepts a boolean array as input.

**Comment by seanlaw** [comment]
> Now, I think I should have put it on hold till I find the reason behind not getting error.

So, is anything actually wrong then? It sounds like all 3 points that you made originally are fine?

**Comment by NimaSarajpoor** [comment]
> So, is anything actually wrong then? It sounds like all 3 points that you made originally are fine? If so, the PR can probably be closed?

Yes. Everything is fine. If you think the changes in the PR is not necessary, please feel free to close this issue and the PR.
