### ISSUE TITLE
`mpdist`: Allow user to chose between `stump` and `mstump` (or figure out the best option automatically)

### ISSUE THREAD

**Issue by nucflash** [TDAmeritrade/stumpy#865]
Hi, thanks for the great software! This seems to be one of the best implementations for matrix profiling all around. 

While working my way through the [MPDist Tutorial](https://github.com/TDAmeritrade/stumpy/blob/main/docs/Tutorial_MPdist.ipynb), I realized that I cannot pass multi-dimensional timeseries to `mpdist`. The change seems to be trivial, since `mpdist` calls `stump` internally. I was surprised that the user can't set this option, or that `mpdist` doesn't choose `stump`/`mstump` by itself depending on the shape of the timeseries.

**Comment by seanlaw** [comment]
@nucflash Thank you for your kind words. The reason why `mpdist` cannot allow multi-dimensional time series is because it isn't clear what the result should/would be. Note that a multi-dimensional matrix profile is not simply multiple 1-D matrix profiles stacked on top of each other. Anything that is multi-dimensional in matrix profiles is much more complex and much harder to interpret.

If you are merely looking to process multiple 1-D time series then looping over each time series is still your best bet. Maybe I've misunderstood your question so please feel free to clarify.

**Comment by nucflash** [comment]
Thanks Sean for the prompt reply. I read Matrix Profile VI, and I now understand your point about complexity better. 

I'm considering clustering timeseries of events that are described by multiple timeseries, e.g., position and momentum. I could multiply or somehow "combine" the multiple timeseries so that they become 1D and I can run `mpdist`, but I'm interested in hearing more of your idea about looping over them. Would you care to elaborate a bit more?

**Comment by nucflash** [comment]
Unfortunately I cannot share much about the data. What I share is that I read many threads here and I found nice hints in your comments. I also went through many of the tutorials, and I read a few more papers on Matrix Profile, and I managed to piece together a way that allows me to consider multiple dimensions simultaneously. Thanks again for the trove of information that you've built!
