### ISSUE TITLE
Add Type Hints or Annotations to Code

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#92]
This may be a good idea for future development as it brings some nice things to editors.

Here is a nice summary how-to:

https://inventwithpython.com/blog/2019/11/24/type-hints-for-busy-python-programmers/

**Comment by cydave** [comment]
hello :wave: I could take a stab at this.
I'm not aquatinted with your code base and would rely on the doc strings if that's fine with you.

**Comment by seanlaw** [comment]
@cydave That would be super helpful and we’d welcome a PR! The docstrings should be up to date and I am always here to answer any questions that you may have. I have no experience with Type Hints and whether there are:

1. Compatibility concerns (check our dependencies)
2. Things we should add for continuous integration with Azure Pipelines

Please fork this repo and we’ll go from there. Do you have experience with Type Hints? Is there anything we should discuss before proceeding? Is this project to small to warrant it? I am totally open to not adding it as well.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cydave** [comment]
Type hints convey information about what you'd expect the user (or developer) of your project to pass. So I'd argue adding type hints is a good thing. 

About the compatibility concerns:  
Type hints themselves were introduced in Python 3.6, but since your project clearly states older versions are not supported, this shouldn't be an issue. If you use the run of the mill python (without mypy installed) the type hints are simply ignored during execution. So it's up to the developer to decide if they want to *only* convey additional information about their code, or if they enforce type checking by having mypy installed.

Personally I've only ever used type hints to convey information for developers on what to pass in.
This sufficed for my use cases for quite a while now.

Important to note is that numpy does not have stable type hints. This means you can't enforce strict type checking (without excluding most of the dependencies you pull in) via mypy.

**Comment by seanlaw** [comment]
This sounds great and I am on board! Thanks again for contributing to our library

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cydave** [comment]
This PR has moved to #96
