### ISSUE TITLE
Incorrect MIN Python Version in README 

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#957]
The MIN Python version mentioned In `README.rst` is outdated (see the following line)

```
STUMPY supports [Python 3.7+](https://python3statement.org/) and, due to ...
```

Is it okay to just change it to `3.8+`? Because STUMPY has not tested the support for `python 3.12` yet in `.github/workflows/github-actions.yml`.

**Comment by joehiggi1758** [comment]
Hey All - hope you're having a wonderful day!

Would it be alright if I take this one? I'm new to OSS contributions, but want to help!

**Comment by seanlaw** [comment]
@joehiggi1758 Thank you for your interest in contributing to STUMPY. Yes, please feel free to take this one! It looks like we need:

1. Update the Python version listed in the README.md file
2. Add a note to the `pypi.sh` file for things to update/change when we upload a new version to PyPI
3. Check if we have 3.7 hardcoded anywhere else in our docs/tutorials?

**Comment by joehiggi1758** [comment]
@seanlaw thanks so much for the opportunity to help, I'm on it!

1. Done!
2. Can you expand a bit here?
3. Currently working on!

Will try to knock this one out by end of week!

**Comment by seanlaw** [comment]
> Can you expand a bit here?

So, the [pypi.sh](https://github.com/TDAmeritrade/stumpy/blob/main/pypi.sh) file is a simple helper script that we use to help us upload the latest package version to PyPI. Since this uploading task is only performed once in a while, we also store "last minute steps" (as comments) in this file to remind us of the additional things that we need to check off our list BEFORE we upload to PyPI. In this particular case, we should add `f) README.md` to the comments of the pypi.sh file of "things-to-do":

```
# 5. Bump minimum versions and dependencies
#    a) setup.py
#    b) requirements.txt
#    c) environment.yml
#    d) .github/worflows/github-actions.yml
#    e) recipes/meta.yaml in conda-feedstock
#    f) README.md
# 6. Commit all above changes as the latest version number and push
```

Currently, the list ends at `5. e)` but we should add a `5. f)` as shown above. Let me know if that makes sense or please seek further clarification

**Comment by seanlaw** [comment]
@joehiggi1758 Once this is done then somebody can work on issue #973, which is somewhat related to this

**Comment by joehiggi1758** [comment]
@seanlaw sounds great! I'd be happy to snag #973 if nobody else has (after I close this one out)! 

Apologies for the likely naïve question - but I can't seem to get my local repository to pass the full set of tests in "test.sh" and keep getting the following. 

![image](https://github.com/TDAmeritrade/stumpy/assets/46200959/d7af293e-8542-4455-8683-b8716573bf2e)

I've followed the Stumpy setup docs exactly and have tried everything I can think of - any direction on how to clear would be much appreciated!

**Comment by joehiggi1758** [comment]
@seanlaw thank you very much for the direction here - it was super helpful! 

I figured out the issue - and I do believe this warrants an update to the 'Contributing Guide' and perhaps an update to 'test.sh'. I had cloned STUMPY locally to my installation of MS VS Code (not using Anaconda), and when I would run 'test.sh' in the STUMPY root directory, it would actually look through my virtual environment (which I had called .venv) and run tests on all files contained, including isolated package installations, hence why my file count was insanely high ~2900 in the above output.

I switched to using Anaconda and was able to get everything working - I have submitted a pull request for the above! I'm open to any and all feedback as I'm eager to learn, please let me know how I can improve moving forward! 

Once this issue closes, I will happily pick up #973 if it's still open!

**Comment by seanlaw** [comment]
> I figured out the issue - and I do believe this warrants an update to the 'Contributing Guide' and perhaps an update to 'test.sh'. I had cloned STUMPY locally to my installation of MS VS Code (not using Anaconda), and when I would run 'test.sh' in the STUMPY root directory, it would actually look through my virtual environment (which I had called .venv) and run tests on all files contained, including isolated package installations, hence why my file count was insanely high ~2900 in the above output.

Hmm, I've not used `.venv` virtual environments before but, typically, `test.sh` would simply execute in the current working directory (i.e., the root `stumpy` directory). There's nothing special about `test.sh` so it wouldn't go looking in random places. In VSCode, within the VSCode terminal, what happens when you type `pwd`? Maybe you still need to navigate to the root `stumpy` directory within your terminal as well before executing the `test.sh` file? How are you running `test.sh`? From the VSCode terminal or from the VSCode GUI?

**Comment by seanlaw** [comment]
> thank you very much for the direction here - it was super helpful!

No, thank YOU! Sometimes, contributing (to Python packages) can be front loaded with frustrating issues like this that have nothing to do with the actual Python coding and many people quit due to how daunting it feels. So, your persistence is greatly appreciated! 

> I'm open to any and all feedback as I'm eager to learn, please let me know how I can improve moving forward!

You have the right mindset so let's learn and make progress together! :)
