### ISSUE TITLE
NumPy 2.0 issue: `np.NINF` was removed

### ISSUE THREAD

**Issue by mactsouk** [TDAmeritrade/stumpy#997]
I am trying to use `stumpy` with NumPy 2.0 and I get the following error message:

AttributeError: `np.NINF` was removed in the NumPy 2.0 release. Use `-np.inf` instead.

The issue occurs three times in `stump.py` file.
Thank you!

**Comment by seanlaw** [comment]
@mactsouk Please see issue #989. This problem was fixed in PR 93ba25a and is now in the main development branch. To install the latest development version of stumpy, please try:

```
git clone https://github.com/TDAmeritrade/stumpy.git
cd stumpy
python -m pip install .
```

This new (NumPy-2.0-compatible) version will be available in PyPI/conda-forge in the coming weeks. Otherwise, try downgrading NumPy.

**Comment by mactsouk** [comment]
@seanlaw Thanks and thank you for `stumpy`!

**Comment by seanlaw** [comment]
You bet, @mactsouk! I'd love to know what you are using STUMPY for and if you plan to write about matrix profiles? 😊

**Comment by mactsouk** [comment]
@seanlaw I am currently doing research on time series data mining and I am using the `stumpy` implementation of MPdist.
